@Hexagonal.Solution.Template.Host.WebApp_HostAddress = https://localhost:7175

GET {{Hexagonal.Solution.Template.Host.WebApp_HostAddress}}/order/2
Accept: application/json

###
POST {{Hexagonal.Solution.Template.Host.WebApp_HostAddress}}/order
Content-Type: application/json

{
  "Description": "John's computer",
  "Items": [
    {
      "Name": "Computer",
      "Description": "Surface 2",
      "Value": 1000
    },
    {
      "Name": "Mouse",
      "Description": "Microsoft mouse",
      "Value": 99
    },
    {
      "Name": "Keyboard",
      "Description": "Microsoft keyboard",
      "Value": 199
    }
  ]
}
###
