name: hexagonal-solution-template

services:
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:13
    ports:
      - "18888:18888"
      - "18889:18889"
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true

  mockApi:
    build:
      context: ./mocks/MockApi
      dockerfile: Dockerfile
    ports:
      - "5012:5012"
    networks:
      - hexagonal_solution_template_network

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 15s
    networks:
      - hexagonal_solution_template_network

networks:
  hexagonal_solution_template_network:
    driver: bridge
