name: hexagonal-solution-template-bff-load-tests

services:
  k6:
    container_name: k6
    image: grafana/k6:1.4.2
    depends_on:
      bff:
        condition: service_healthy
    ports:
      - "6565:6565"
    environment:
      - WEBAPP_URL=http://bff:5011
      - K6_SUMMARY_MODE=full
      - K6_WEB_DASHBOARD=true
      - K6_WEB_DASHBOARD_EXPORT=html-report.html
      - VUS=1000
      - DURATION=180s
      - GRACEFUL_STOP=10s
    command: ["run", "/LoadTests/scriptHttp.js", ]
    volumes:
      - ./tests/LoadTests:/LoadTests

  bff:
    container_name: bff
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5011:5011"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5011/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - PYROSCOPE_APPLICATION_NAME=Hexagonal.Solution.Template
      - PYROSCOPE_SERVER_ADDRESS=http://alloy:9999

  mock-api:
    extends:
      file: docker-compose-local.yml
      service: mock-api

  redis:
    extends:
      file: docker-compose-local.yml
      service: redis

  alloy:
    extends:
      file: docker-compose-local.yml
      service: alloy

  prometheus:
    extends:
      file: docker-compose-local.yml
      service: prometheus

  loki:
    extends:
      file: docker-compose-local.yml
      service: loki

  grafana:
    extends:
      file: docker-compose-local.yml
      service: grafana

  tempo-init:
    extends:
      file: docker-compose-local.yml
      service: tempo-init

  tempo:
    extends:
      file: docker-compose-local.yml
      service: tempo

  pyroscope:
    extends:
      file: docker-compose-local.yml
      service: pyroscope
