name: hexagonal-solution-template-load-tests

services:
  k6:
    image: grafana/k6:1.4.2
    depends_on:
      webapp:
        condition: service_healthy
    ports:
      - "6565:6565"
    environment:
      - WEBAPP_URL=http://webapp:5000
      - K6_SUMMARY_MODE=full
    command: ["run", "/LoadTests/scriptHttp.js", ]
    volumes:
      - ./tests/LoadTests:/LoadTests
    networks:
      - hexagonal_solution_template_network

  bff:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LOGGING__LOGLEVEL__DEFAULT=Warning
      - LOGGING__LOGLEVEL__MICROSOFT=Warning
      - OTEL_SERVICE_NAME=Hexagonal.Solution.Template.Bff
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=http://aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=load-tests
    networks:
      - hexagonal_solution_template_network

  mockApi:
    extends:
      file: docker-compose.yml
      service: mockApi

  aspire-dashboard:
    extends:
      file: docker-compose.yml
      service: aspire-dashboard

  redis:
    extends:
      file: docker-compose.yml
      service: redis

networks:
  hexagonal_solution_template_network:
    driver: bridge
