name: hexagonal-solution-template-bff-load-tests

services:
  k6:
    image: grafana/k6:1.4.2
    depends_on:
      webapp:
        condition: service_healthy
    ports:
      - "6565:6565"
    environment:
      - WEBAPP_URL=http://webapp:5000
      - K6_SUMMARY_MODE=full
    command: ["run", "/LoadTests/scriptHttp.js", ]
    volumes:
      - ./tests/LoadTests:/LoadTests
    networks:
      - hexagonal_solution_template_network

  bff:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OTEL_SERVICE_NAME=Hexagonal.Solution.Template.Bff
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=load-tests
    networks:
      - hexagonal_solution_template_network

  mock-api:
    extends:
      file: docker-compose.yml
      service: mock-api

  redis:
    extends:
      file: docker-compose.yml
      service: redis

    alloy:
    extends:
      file: docker-compose-grafana.yml
      service: alloy
    networks:
      - hexagonal_solution_template_bff_network

  prometheus:
    extends:
      file: docker-compose-grafana.yml
      service: prometheus
    networks:
      - hexagonal_solution_template_bff_network

  loki:
    extends:
      file: docker-compose-grafana.yml
      service: loki
    networks:
      - hexagonal_solution_template_bff_network

  grafana:
    extends:
      file: docker-compose-grafana.yml
      service: grafana
    networks:
      - hexagonal_solution_template_bff_network

  tempo-init:
    extends:
      file: docker-compose-grafana.yml
      service: tempo-init
    networks:
      - hexagonal_solution_template_bff_network

  memcached:
    extends:
      file: docker-compose-grafana.yml
      service: memcached
    networks:
      - hexagonal_solution_template_bff_network

  tempo:
    extends:
      file: docker-compose-grafana.yml
      service: tempo
    networks:
      - hexagonal_solution_template_bff_network

networks:
  hexagonal_solution_template_bff_network:
    driver: bridge
