name: hexagonal-solution-template-full

services:
  postgres:
    image: &postgresImage postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "cY5VvZkkh4AzES"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "OrderDb"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 10s
      retries: 10
      start_period: 10s
    ports:
      - "5432:5432"

  postgres-init:
    image: *postgresImage
    container_name: postgres-init
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./scripts/sql/migrations.sql:/tmp/migrations.sql
      - ./scripts/sql/seeds.sql:/tmp/seeds.sql
    command:
      - /bin/sh
      - -c
      - |
        psql -h postgres -U postgres -d OrderDb -f /tmp/migrations.sql &&
        psql -h postgres -U postgres -d OrderDb -f /tmp/seeds.sql
    environment:
      PGPASSWORD: "cY5VvZkkh4AzES"

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    command: >
      bash -c "rabbitmq-plugins enable rabbitmq_prometheus &&
               docker-entrypoint.sh rabbitmq-server"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 10s