name: hexagonal-solution-template-full

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: "cY5VvZkkh4AzES"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "OrderDb"
    networks:
      - hexagonal_solution_template_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 10s
      retries: 10
      start_period: 15s
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:9.12.0
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5050:80"
    networks:
      - hexagonal_solution_template_network

  postgres-init:
    image: postgres:17-alpine
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - hexagonal_solution_template_network
    volumes:
      - ./scripts/migrations.sql:/tmp/migrations.sql
      - ./scripts/seeds.sql:/tmp/seeds.sql
    command:
      - /bin/sh
      - -c
      - |
        psql -h postgres -U postgres -d postgres -f /tmp/migrations.sql &&
        psql -h postgres -U postgres -d postgres -f /tmp/seeds.sql
    environment:
      PGPASSWORD: "cY5VvZkkh4AzES"

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:13
    ports:
      - "18888:18888"
      - "18889:18889"
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 15s
    networks:
      - hexagonal_solution_template_network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 15s
    networks:
      - hexagonal_solution_template_network

networks:
  hexagonal_solution_template_network:
    driver: bridge
