CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418162254_CreateTables') THEN
    CREATE TABLE "Notification" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "NotificationType" integer NOT NULL,
        "NotificationStatus" character varying(50) NOT NULL,
        "Message" jsonb,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" text,
        "CreatedByTimezoneId" text NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" text,
        "UpdatedByTimezoneId" text,
        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
        "DeletedAt" timestamp with time zone,
        "DeletedBy" text,
        CONSTRAINT "PK_Notification" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418162254_CreateTables') THEN
    CREATE TABLE "Order" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Description" text NOT NULL,
        "Total" numeric(18,2) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" text,
        "CreatedByTimezoneId" text NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" text,
        "UpdatedByTimezoneId" text,
        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
        "DeletedAt" timestamp with time zone,
        "DeletedBy" text,
        CONSTRAINT "PK_Order" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418162254_CreateTables') THEN
    CREATE TABLE "Item" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text NOT NULL,
        "Value" numeric(18,2) NOT NULL,
        "OrderId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedBy" text,
        "CreatedByTimezoneId" text NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedBy" text,
        "UpdatedByTimezoneId" text,
        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
        "DeletedAt" timestamp with time zone,
        "DeletedBy" text,
        CONSTRAINT "PK_Item" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Item_Order_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Order" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418162254_CreateTables') THEN
    CREATE INDEX "IX_Item_OrderId" ON "Item" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418162254_CreateTables') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260418162254_CreateTables', '10.0.5');
    END IF;
END $EF$;
COMMIT;

