@WebApp_HostAddress = https://localhost:7175

###
GET {{WebApp_HostAddress}}/health HTTP/2
Accept: application/json

###
GET {{WebApp_HostAddress}}/live HTTP/2

###
GET {{WebApp_HostAddress}}/ready HTTP/2

###
GET {{WebApp_HostAddress}}/orders/6 HTTP/2
CorrelationId: {{$guid}}
Accept: application/json

###
POST {{WebApp_HostAddress}}/orders HTTP/2
Content-Type: application/json

{
  "CorrelationId": "{{$guid}}",
  "Description": "John's computer",
  "Items": [
    {
      "Name": "Computer",
      "Description": "Surface 2",
      "Value": 1000
    },
    {
      "Name": "Mouse",
      "Description": "Microsoft mouse",
      "Value": 99
    }
  ]
}

###
POST {{WebApp_HostAddress}}/orders/paginated HTTP/2
Content-Type: application/json

{
  "CorrelationId": "{{$guid}}",
  "Page": 1,
  "PageSize": 1
}

###
POST {{WebApp_HostAddress}}/orders/paginated HTTP/2
Content-Type: application/json

{
  "CorrelationId": "{{$guid}}",
  "Page": 1,
  "PageSize": 10,
  "SearchByValues": {
    "Description": "client"
  }
}

