@WebApp_HostAddress = https://localhost:7175

###
GET {{WebApp_HostAddress}}/health
Accept: application/json

###
GET {{WebApp_HostAddress}}/live

###
GET {{WebApp_HostAddress}}/ready

###
GET {{WebApp_HostAddress}}/orders/1/{{$guid}}
Accept: application/json

###
POST {{WebApp_HostAddress}}/orders
Content-Type: application/json

{
  "CorrelationId": "{{$guid}}",
  "Description": "John's computer",
  "Items": [
    {
      "Name": "Computer",
      "Description": "Surface 2",
      "Value": 1000
    },
    {
      "Name": "Mouse",
      "Description": "Microsoft mouse",
      "Value": 99
    },
    {
      "Name": "Keyboard",
      "Description": "Microsoft keyboard",
      "Value": 199
    }
  ]
}
###

POST {{WebApp_HostAddress}}/orders/paginated
Content-Type: application/json

{
  "CorrelationId": "{{$guid}}",
  "PageNumber": 1,
  "PageSize": 5,
  "SearchByValues": {
    "Description": "client"
  }
}
