@WebApp_HostAddress = https://localhost:7175

###
GET {{WebApp_HostAddress}}/health
Accept: application/json

###
GET {{WebApp_HostAddress}}/orders/1/e1e2ef94-a49c-4f23-8148-5af97a25e06f
Accept: application/json

###
POST {{WebApp_HostAddress}}/orders
Content-Type: application/json

{
  "CorrelationId": "{{$guid}}",
  "Description": "John's computer",
  "Items": [
    {
      "Name": "Computer",
      "Description": "Surface 2",
      "Value": 1000
    },
    {
      "Name": "Mouse",
      "Description": "Microsoft mouse",
      "Value": 99
    },
    {
      "Name": "Keyboard",
      "Description": "Microsoft keyboard",
      "Value": 199
    }
  ]
}
###
