services:
  mock-api:
    build:
      context: .
      dockerfile: Dockerfile.MockApi
    ports:
      - "5012:5012"
    environment:
      ASPNETCORE_URLS: http://+:5012

  webui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mock-api
    environment:
      ASPNETCORE_URLS: http://+:8080