name: hexagonal-solution-template-webui-e2e

services:
  mock-api:
    build:
      context: .
      dockerfile: Dockerfile.MockApi
    ports:
      - "5014:5014"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OTEL_SERVICE_NAME=Hexagonal.Solution.Template.Bff.MockApi
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - PYROSCOPE_APPLICATION_NAME=Hexagonal.Solution.Template.WebUi.MockApi
      - PYROSCOPE_SERVER_ADDRESS=http://alloy:9999
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5013:5013"
    depends_on:
      - mock-api
    environment:
      - ASPNETCORE_ENVIRONMENT=LoadTesting
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - PYROSCOPE_APPLICATION_NAME=Hexagonal.Solution.Template.WebUi
      - PYROSCOPE_SERVER_ADDRESS=http://alloy:9999
