name: hexagonal-solution-template-simple

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "cY5VvZkkh4AzES"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "OrderDb"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 10s
      retries: 10
      start_period: 10s
    ports:
      - "5432:5432"

  db-migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    environment:
      - CONNECTION_STRING=Host=postgres;Port=5432;Database=OrderDb;Username=postgres;Password=cY5VvZkkh4AzES
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 10s
