name: hexagonal-solution-template-simple-WebUi-e2e

services:
  WebUi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5015:5015"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=E2E
      - ConnectionStrings__OrderDb=Host=postgres;Port=5432;Database=OrderDb;Username=postgres;Password=cY5VvZkkh4AzES

  postgres:
    image: &postgresImage postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "cY5VvZkkh4AzES"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "OrderDb"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 10s
      retries: 10
      start_period: 10s
    ports:
      - "5432:5432"

  postgres-init:
    image: *postgresImage
    container_name: postgres-init
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./scripts/sql/migrations.sql:/tmp/migrations.sql
      - ./scripts/sql/seeds.sql:/tmp/seeds.sql
    command:
      - /bin/sh
      - -c
      - |
        psql -h postgres -U postgres -d OrderDb -f /tmp/migrations.sql &&
        psql -h postgres -U postgres -d OrderDb -f /tmp/seeds.sql
    environment:
      PGPASSWORD: "cY5VvZkkh4AzES"
