name: hexagonal-solution-template-simple-webui

services:
  postgres:
    image: &postgresImage postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "cY5VvZkkh4AzES"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "OrderDb"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 10s
      retries: 10
      start_period: 10s
    ports:
      - "5432:5432"

  db-migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    environment:
      - ConnectionStrings__OrderDb=Host=postgres;Port=5432;Database=OrderDb;Username=postgres;Password=cY5VvZkkh4AzES
    depends_on:
      postgres:
        condition: service_healthy

  aspire-dashboard:
    container_name: aspire-dashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:13.3.0
    environment:
      - ASPIRE_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
      - DOTNET_DASHBOARD_OTLP_HTTP_ENDPOINT_URL=http://+:4318
      - DOTNET_DASHBOARD_OTLP_ENDPOINT_URL=http://+:4317
    ports:
      - 18888:18888
      - 4317:4317
