on:
  workflow_call:  
    inputs:
      package_version:
        required: true
        type: string
    secrets:
      nuget_api_key:
        required: true

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      
    - name: Build
      run: dotnet build -c Release
      
    - name: Pack
      run: dotnet pack -p:PackageVersion=${{ inputs.package_version}}
      
    - name: Push to NuGet
      run: dotnet nuget push "./bin/Release/*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json