name: Publish template in Nuget.org

on: 
  workflow_dispatch:

jobs:
  validate-full-template:
    uses: gpreviatti/github-actions-templates/.github/workflows/dotnet-validate.yml@v1
    with:
      build_path: "./templates/Full"
      project: "hexagonal-solution-template-full"
      organization: "gpreviatti"
      unit_test_project_path: "./templates/Full/tests/UnitTests/"
      dotnet_version: "${{ vars.PROJECT_DOTNET_VERSION }}"
      domain_stryker_config_path: "./templates/Full/tests/UnitTests/stryker-config-domain.json"
      application_stryker_config_path: "./templates/Full/tests/UnitTests/stryker-config-application.json"
      integration_test_project_path: "./templates/Full/tests/IntegrationTests"
      docker_compose_file_path: "./templates/Full/docker-compose.yml"
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}

  validate-bff-template:
    uses: gpreviatti/github-actions-templates/.github/workflows/dotnet-validate.yml@v1
    with:
      build_path: "./templates/Bff"
      project: "hexagonal-solution-template-bff"
      dotnet_version: "${{ vars.PROJECT_DOTNET_VERSION }}"
      integration_test_project_path: "./templates/Bff/tests/IntegrationTests"
      docker_compose_file_path: "./templates/Bff/docker-compose.yml"
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}

  pack-and-publish:
    needs: [validate-full-template, validate-bff-template]
    uses: gpreviatti/github-actions-templates/.github/workflows/dotnet-pack.yml@v1
    with:
      dotnet_version: "${{ vars.PROJECT_DOTNET_VERSION }}"
      package_version: "10.1.0"
    secrets:
      nuget_api_key: ${{ secrets.NUGET_API_KEY }}
