name: Publish template in Nuget.org

on: 
  workflow_dispatch:

jobs:
  validate-template-full:
    name: Validate Full Template
    uses: gpreviatti/github-actions-templates/.github/workflows/dotnet-validate-full.yml@v1
    with:
      build_path: "./templates/Full"
      unit_test_project_path: "./templates/Full/tests/UnitTests/"
      dotnet_version: "${{ vars.PROJECT_DOTNET_VERSION }}"
      stryker_domain_config_path: "./templates/Full/tests/UnitTests/stryker-config-domain.json"
      stryker_application_config_path: "./templates/Full/tests/UnitTests/stryker-config-application.json"
      stryker_publish_dashboard_report: true
      stryker_dashboard_module_domain: "full-domain"
      stryker_dashboard_module_application: "full-application"
      integration_test_project_path: "./templates/Full/tests/IntegrationTests"
      docker_compose_file_path: "./templates/Full/docker-compose.yml"
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      stryker_dashboard_api_key: ${{ secrets.STRYKER_DASHBOARD }}

  validate-template-bff:
    name: Validate BFF Template
    uses: gpreviatti/github-actions-templates/.github/workflows/dotnet-validate-bff.yml@v1
    with:
      build_path: "./templates/Bff"
      dotnet_version: "${{ vars.PROJECT_DOTNET_VERSION }}"
      integration_test_project_path: "./templates/Bff/tests/IntegrationTests"
      docker_compose_file_path: "./templates/Bff/docker-compose.yml"
  
  validate-contracts-template:
    name: Validate Contracts Template
    uses: gpreviatti/github-actions-templates/.github/workflows/dotnet-validate-contracts.yml@v1
    with:
      build_path: "./templates/Contracts"
      dotnet_version: "${{ vars.PROJECT_DOTNET_VERSION }}"
      test_project_path: "./templates/Contracts/tests/UnitTests/"
      stryker_config_path: "./templates/Contracts/tests/UnitTests/stryker-config.json"
      stryker_publish_dashboard_report: true
      stryker_dashboard_module: "contracts"
    secrets:
      stryker_dashboard_api_key: ${{ secrets.STRYKER_DASHBOARD }}

  validate-template-webui:
    name: Validate WebUi Template
    uses: gpreviatti/github-actions-templates/.github/workflows/dotnet-validate-webui.yml@v1
    with:
      build_path: "./templates/WebUi"
      dotnet_version: "${{ vars.PROJECT_DOTNET_VERSION }}"
      test_project_path: "./templates/WebUi/tests/UnitTests/"
      stryker_config_path: "./templates/WebUi/tests/UnitTests/stryker-config.json"
      stryker_publish_dashboard_report: true
      stryker_dashboard_module: "webui"
    secrets:
      stryker_dashboard_api_key: ${{ secrets.STRYKER_DASHBOARD }}

  pack-and-publish:
    name: Pack and Publish Template
    needs: [validate-template-full, validate-template-bff, validate-contracts-template, validate-template-webui]
    uses: gpreviatti/github-actions-templates/.github/workflows/dotnet-pack.yml@v1
    with:
      dotnet_version: "${{ vars.PROJECT_DOTNET_VERSION }}"
      package_version: "10.10.0"
    secrets:
      nuget_api_key: ${{ secrets.NUGET_API_KEY }}

