name: Validate

on: 
  pull_request:
  workflow_dispatch:

jobs:
  validate-full-template:
    uses: gpreviatti/github-actions-templates/.github/workflows/dotnet-validate.yml@v1
    with:
      project: "hexagonal-solution-template-full"
      organization: "gpreviatti"
      unit_test_project_path: "./Full/templates/tests/UnitTests/"
      unit_test_verbosity: 'd'
      dotnet_version: "${{ vars.PROJECT_DOTNET_VERSION }}"
      domain_stryker_config_path: "./Full/templates/tests/UnitTests/stryker-config-domain.json"
      application_stryker_config_path: "./Full/templates/tests/UnitTests/stryker-config-application.json"
      integration_test_project_path: "./Full/templates/tests/IntegrationTests"
      docker_compose_file_path: "./Full/templates/docker-compose.yml"
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}

  validate-minimal-template:
    uses: gpreviatti/github-actions-templates/.github/workflows/dotnet-validate.yml@v1
    with:
      project: "hexagonal-solution-template-minimal"
      organization: "gpreviatti"
      dotnet_version: "${{ vars.PROJECT_DOTNET_VERSION }}"
      integration_test_project_path: "./Minimal/templates/tests/IntegrationTests"
      docker_compose_file_path: "./Minimal/templates/docker-compose.yml"
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}